-- Exercise 1: Count the number of trips in January 2022

select 
  extract(month from pickup_datetime) as month_of_trips,
  count(*) as number_of_trips_January_2022
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
where 
  extract(month from pickup_datetime) = 1
group by 
  month_of_trips;


-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023

select 
  sum(total_amount) as total_amount
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;


-- Exercise 3: Find the most popular pickup location

select 
  pickup_location_id,
  count(pickup_location_id) as count_pickup_location_id
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
group by
  pickup_location_id
order by 
  count_pickup_location_id desc
limit 1;


-- Exercise 4: Analyze the number of trips per hour of the day

select 
  EXTRACT(hour from pickup_datetime) as pickup_hour,
  count(*) as count_trips
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
group by
  pickup_hour
order by
  pickup_hour;


  -- Exercise 5: Calculate the average trip distance

select 
  avg(trip_distance) as avg_trip_distance
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;


-- Exercise 6: Find the longest trip by distance

select 
  max(trip_distance) as avg_trip_distance
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;


-- Exercise 7: Calculate the total number of passengers by payment type

select 
  payment_type,
  sum(passenger_count) as tottal_number_of_passengers
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
group by
  payment_type
order by 
  tottal_number_of_passengers desc;
  

-- Exercise 8: Find the most common drop-off location for trips paid by payment type 1

  select 
  dropoff_location_id,
  count(dropoff_location_id) as count_dropoff_location_id
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
where 
  payment_type = '1'
group by 
  dropoff_location_id
order by 
  count_dropoff_location_id desc
limit 1;


-- Exercise 9: Calculate the total number of trips that had more than 4 passengers

select 
  count(*) as total_numbers_of_trips
from
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
where 
  passenger_count > 4;


  -- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance

select 
  avg(fare_amount)
from 
  bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
where
  trip_distance >
                    (select 
                      avg(trip_distance) as avg_trip_distance
                    from
                      bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022);
